version: '3'
# docker volume create --name data -d local
services:
  db-text-sum:
    image: 'postgres:latest'
    ports:
      - '${DB_PORT}:5432'
    environment:
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    expose:
      - '${DB_PORT}'

  db-monitor-text-sum:
    image: 'dpage/pgadmin4'
    depends_on:
      - db-text-sum
    ports:
      - '${DB_MONITOR_PORT}:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_USER}
      PGADMIN_DEFAULT_PASSWORD: ${DB_ROOT_PASSWORD}
    
volumes:
  data:
    external: true
