export enum REFERENCE_TYPE {
  /*
    CUSTOMER RELATED
  */
  CUSTOMER_ID_CARD_FRONT_IMAGE,
  CUSTOMER_ID_CARD_BACK_IMAGE,
  CUSTOMER_PROFILE_IMG,
  /*
    DRIVER RELATED 
  */
  DRIVER_ID_CARD_FRONT_IMAGE,
  DRIVER_ID_CARD_BACK_IMAGE,
  DRIVER_PROFILE_IMG,
  /*
    TRUCK_OWNER_RELATED
  */

  TRUCK_OWNER_ID_CARD_FRONT_IMAGE,
  TRUCK_OWNER_ID_CARD_BACK_IMAGE,
  TRUCK_OWNER_PROFILE_IMG,
  COMPANY_ICON,
  BUSINESS_LICENSE,
  TRUCK_CERTIFICATE,

  DRIVER_LICENSE,

  /*
    ORDER_RELATED
  */

  ORDER_DOCUMENT,
}
